### PR TITLE
Unit Testing for linear_fit.py and edits to python to make it pylint compliant.

### PR DESCRIPTION
**Pull request by SchrodingersStruggle**
Added several edits to linear_fit.py such as the following:

- Added functionality to specify headers in csv uploaded, doesn't have to be 'x', 'y', and 'sigma' anymore.
- Added many error cases to add specific print in error output in common error cases.
- Removed the 'weight' variable as it was unnecessary, and there were too many defined variables for pylint.
- Redefined some variable like "S" to be pylint compliant.
- Added section to only call on the example usage if the module itself is being ran directly. Avoids unit testing errors.

Added test_linear_fit.py

Added a blank CSV. **THIS IS ON PURPOSE, DO NOT DELETE IT**
Unit testing uses this blank CSV to add custom data and remove it, to test for specific cases the code handles.

### CODE REVIEW

**Comment by SchrodingersStruggle** [comment]
Okay, pylint likes my code but flake8 doesn't so I will make edits.

**Comment by SchrodingersStruggle** [comment]
The remaining issues from flake8 actually are from the cython code @avgagliardo. Is there any suggestions on what to do about that?

**Comment by laserlab** [comment]
@ubsuny/cp1-24 Anyone who wants to review this?

**Comment by ojha-aditya** [comment]
I can review this.

**Comment by ojha-aditya** [comment]
Do we check for both code and linting?

**Comment by kylemasc917** [comment]
Yes

**Comment by kylemasc917** [comment]
Make sure to check the code itself and also check that there are not any minor linting errors like whitespace or indentation errors etc...

**Comment by SchrodingersStruggle** [comment]
@ojha-aditya I added you as a reviewer, so it should be available now

**Comment by kylemasc917** [comment]
@ojha-aditya Make sure to review this as soon as possible so it can be merged.

**Review by ojha-aditya — APPROVED** [review]
The code is good with pylint, can be merged.

**Comment by HeshamElsaman** [comment]
Great, merging.

**Pull request merged**
