### PR TITLE
Added code to read data from csv file

### PR DESCRIPTION
**Pull request by jkblc**
Added code to read data from csv file. There is some existing code in another file to do this that doesn't seen to work and crashes the program

### CODE REVIEW

**Comment by HeshamElsaman** [comment]
@abruns123 I added you as a reviewer to this.

**Review by abruns123 — CHANGES_REQUESTED** [review]
Most immediately, there needs to be a unit test module to go with this. Also needs some work to pass the pylint test such as a doc string for the module and reduction of empty spaces after certain lines.

**Comment by jkblc** [comment]
I have fixed some pylint errors and I believe the remainder of the errors are in code that I have not written but was merged with errors.

**Comment by jkblc** [comment]
The module already had a docstring

**Comment by jkblc** [comment]
I have addressed the requested issues

**Comment by kylemasc917** [comment]
@abruns123 if you could please review this as soon as possible so it can be merged.

**Review by abruns123 — APPROVED** [review]
Looks all good now. Should be fine to be merged.

**Pull request merged**
