### PR TITLE
Created a requirements text file with useable libaries.

### PR DESCRIPTION
**Pull request by kylemasc917**
Drafted a requirements.txt file from previous assignments for main repository that contains the useable packets including cython and setuptools. This can be edited to include further libraries as needed.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@HeshamElsaman It seems the Flake8 linter is showing the linting errors here for the entire repository instead of just for this request. Could this be an issue with the workflow or is this running as intended?

**Review by HeshamElsaman — APPROVED** [review]
Looks good. I'm merging this.

**Comment by HeshamElsaman** [comment]
> @HeshamElsaman It seems the Flake8 linter is showing the linting errors here for the entire repository instead of just for this request. Could this be an issue with the workflow or is this running as intended?

I'll work on that.

**Comment by laserlab** [comment]
> @HeshamElsaman It seems the Flake8 linter is showing the linting errors here for the entire repository instead of just for this request. Could this be an issue with the workflow or is this running as intended?

Intended since it wasn’t listed before and everything that fits your github actions filter will be linted.

**Pull request merged**
