### PR TITLE
estimating the age of the universe

### PR DESCRIPTION
**Pull request by zbpetersbuf**
This task is not complete yet (and is due friday) right now as I make the pull request it only contains a folder and the contents of this folder are the module that contains the function that gives the age of the universe

### CODE REVIEW

**Comment by zbpetersbuf** [comment]
Would the correct lables for this pull request be python and documentation? im still a little unsure about what label goes to what

**Comment by zbpetersbuf** [comment]
@p-pxmpo the main function is made, I believe, if you need to message me ill be here, as far as i know this is all I have to do until friday, ill be sure to check my email consistantly

**Comment by p-pxmpo** [comment]
thank you! ill get started on the unit testing and documentation now

**Comment by HeshamElsaman** [comment]
@p-pxmpo I guess it would make sense to me for you to review this one once finished.

**Comment by p-pxmpo** [comment]
> @p-pxmpo I guess it would make sense to me for you to review this one once finished.

I will get on it as soon as i can thanks!

**Comment by HeshamElsaman** [comment]
@p-pxmpo I guess it's finished now, please, review as soon as possible.

**Comment by zbpetersbuf** [comment]
ok i had issue yesterday with commenting the finished product, but should be done now, it now also passes the flake8 test

**Comment by laserlab** [comment]
Adding a number here so #7 can use it for comparing: 242064330 years

**Review by p-pxmpo — COMMENTED** [review]
The function is straight forward and written well, docstrings are well written, this file is ready to be merged. @HeshamElsaman

**Comment by kylemasc917** [comment]
@p-pxmpo make sure you officially approve this and ill merge it right away

**Review by kylemasc917 — APPROVED** [review]
Approved by @p-pxmpo and reapproved by myself due to deadline.

**Comment by kylemasc917** [comment]
I'm merging this now because the deadline is in 45 mins.

**Pull request merged**
