### PR TITLE
Grouped the data of 22 Nebulae and generated the csv file

### PR DESCRIPTION
**Pull request by Cosmos491**
This contains the grouped data of 22 Nebulae on the basis of proximity in both velocity and distance values, reflecting Hubble’s approach to cluster nebulae with similar attributes. The groups correspond visually to the open circles in Figure 1 of Hubble’s 1929 paper, as these groups represent similar regions in the velocity-distance plot.

### CODE REVIEW

**Comment by laserlab** [comment]
@ubsuny/cp1-24 Anyone who wants to review this?

**Comment by haiderabbas007** [comment]
I can do it. I wanted to know whether it is up to myself to take pytest and linting scores into account. Also, should I stick to the following guidelines? Or is there additional criteria for a PR for this HW?
image

**Comment by laserlab** [comment]
Yes take linting into account if applicable. And same with general properties such as the description. The PR template is not merged yet but can be used as a guideline.

**Comment by haiderabbas007** [comment]
> Yes take linting into account if applicable. And same with general properties such as the description. The PR template is not merged yet but can be used as a guideline.

I would need to know whether, to fulfill this task, only the csv file was needed or the code for generating that file as well before I can review.

**Comment by haiderabbas007** [comment]
@Cosmos491 Please add a label, a milestone, a descriptive title, and an in-depth description to your pull request as required by this template: 
image

**Comment by haiderabbas007** [comment]
@Cosmos491 I think you took the values from Table 2 instead of Table 1? Also, the distance column should have $10^6$ parsecs as units.

**Review by haiderabbas007 — CHANGES_REQUESTED** [review]
@Cosmos491 I think you took the values from Table 2 instead of Table 1? Also, the distance column should have $10^6$ parsecs as units.

**Comment by HeshamElsaman** [comment]
@haiderabbas007 @Cosmos491 Any updates guys?

**Comment by Cosmos491** [comment]
@haiderabbas007 I have generated the csv file from Table1. Thanks for pointing that out. Let me know if there is anything else.

**Review by haiderabbas007 — APPROVED** [review]

**Pull request merged**
